### Salvar personagem | usar as rotas /guerreiro  /mago  /ladino
POST http://localhost:8080/personagens/mago
Content-Type: application/json

{
  "nome": "Arthur",
  "forca": 100.0,
  "velocidade": 100.0,
  "vida": 100.0
}

### Listar todos os personagens + por id
GET http://localhost:8080/personagens

### Editar personagem
PUT http://localhost:8080/personagens/
Content-Type: application/json

{
  "nome": "Lucas Editado",
  "forca": 30.0,
  "velocidade": 20.0,
  "vida": 120.0
}

### Excluir personagem
DELETE http://localhost:8080/personagens/155

### Testar ouvir mensagem
POST http://localhost:8080/chat/ouvir
Content-Type: text/plain

Lucas: teste pelo IntelliJ

### Enviar mensagem para o rival
POST http://26.149.198.208:8080/chat/ouvir
Content-Type: text/plain

Lucas: eae, mensagem enviada pelo IntelliJ

### Atacar rival
GET http://localhost:8080/combate/atacar/153

### Testar receber dano no meu personagem
POST http://localhost:8080/combate/apanhar/153
Content-Type: text/plain

25
