### Salvar personagem | usar as rotas /guerreiro  /mago  /ladino
POST http://localhost:8080/personagens
Content-Type: application/json

{
  "nome": "",
  "forca": 100.0,
  "velocidade": 100.0,
  "vida": 100.0
}

### Listar todos os personagens + por id
GET http://localhost:8080/personagens

### Editar personagem
PUT http://localhost:8080/personagens/
Content-Type: application/json

{
  "nome": "",
  "forca": 1000.0,
  "velocidade": 1000.0,
  "vida": 1000.0
}

### Excluir personagem
DELETE http://localhost:8080/personagens/

### Testar ouvir mensagem
POST http://localhost:8080/chat/ouvir
Content-Type: text/plain

Lucas: teste pelo IntelliJ

### Enviar mensagem para o rival
POST http://localhost:8080/chat/msg
Content-Type: text/plain

Lucas: Sabe de nada

### Atacar rival
GET http://localhost:8080/combate/atacar/

### Testar receber dano no meu personagem
POST http://localhost:8080/combate/apanhar/
Content-Type: text/plain

25
